[package]
name = "haw-hamburg-bachelor-thesis"
entrypoint = "lib.typ"
description = "Unofficial template for writing a bachelor-thesis in the HAW Hamburg Faculty of Computer Science and Digital Society style."
categories = ["thesis"]

[template]
path = "src"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
