[package]
name = "haw-hamburg-report"
entrypoint = "lib.typ"
description = "Unofficial template for writing a report in the HAW Hamburg Faculty of Computer Science and Digital Society style."
categories = ["report"]

[template]
path = "src"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
